#!/usr/bin/env bash
# Update Homebrew tap with new wt release

set -euo pipefail

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

log() {
    echo -e "${BLUE}[TAP UPDATE]${NC} $*"
}

success() {
    echo -e "${GREEN}✓${NC} $*"
}

error() {
    echo -e "${RED}✗${NC} $*" >&2
}

warn() {
    echo -e "${YELLOW}⚠${NC} $*"
}

usage() {
    cat << EOF
Usage: $0 <version>

Update the Homebrew tap formula for a new wt release.

Arguments:
    version     Version to update to (e.g., "0.2.1")

This script will:
1. Download the new release tarball
2. Calculate SHA256 checksum  
3. Update the tap repository formula
4. Create and push a commit

Prerequisites:
- Must be run from wt project root
- ../homebrew-wt directory must exist
- GitHub CLI (gh) must be authenticated

Examples:
    $0 0.2.1    # Update tap to version 0.2.1
    $0 1.0.0    # Update tap to version 1.0.0
EOF
}

update_tap_formula() {
    local version="$1"
    local repo_owner="bwishan"
    local repo_name="wt"
    local tap_dir="../homebrew-wt"
    
    log "Updating Homebrew tap for wt v$version"
    
    # Validate directories
    if [ ! -d "$tap_dir" ]; then
        error "Tap directory not found: $tap_dir"
        error "Clone the homebrew-wt repository to the parent directory"
        exit 1
    fi
    
    if [ ! -f "$tap_dir/Formula/wt.rb" ]; then
        error "Formula not found: $tap_dir/Formula/wt.rb"
        exit 1
    fi
    
    # Construct release URL
    local tarball_url="https://github.com/$repo_owner/$repo_name/releases/download/v$version/$repo_name-$version-universal.tar.gz"
    
    log "Calculating SHA256 for $tarball_url"
    
    # Download and calculate SHA256
    local sha256
    sha256=$(curl -sL "$tarball_url" | shasum -a 256 | cut -d' ' -f1)
    
    if [ -z "$sha256" ]; then
        error "Failed to calculate SHA256 for $tarball_url"
        error "Verify that the release exists and the URL is correct"
        exit 1
    fi
    
    success "SHA256: $sha256"
    
    # Update the formula
    log "Updating formula file..."
    
    local formula_file="$tap_dir/Formula/wt.rb"
    local backup_file="$formula_file.backup.$(date +%Y%m%d-%H%M%S)"
    
    # Create backup
    cp "$formula_file" "$backup_file"
    
    # Update URL, SHA256, and version
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS sed
        sed -i '' "s|url \".*\"|url \"$tarball_url\"|" "$formula_file"
        sed -i '' "s|sha256 \".*\"|sha256 \"$sha256\"|" "$formula_file"
        sed -i '' "s|version \".*\"|version \"$version\"|" "$formula_file"
        sed -i '' "s|assert_match \"wt [0-9.]*\"|assert_match \"wt $version\"|" "$formula_file"
    else
        # Linux sed
        sed -i "s|url \".*\"|url \"$tarball_url\"|" "$formula_file"
        sed -i "s|sha256 \".*\"|sha256 \"$sha256\"|" "$formula_file"
        sed -i "s|version \".*\"|version \"$version\"|" "$formula_file"
        sed -i "s|assert_match \"wt [0-9.]*\"|assert_match \"wt $version\"|" "$formula_file"
    fi
    
    # Show changes
    log "Formula updated. Changes:"
    echo
    if command -v diff &> /dev/null; then
        diff "$backup_file" "$formula_file" || true
    else
        echo "=== Updated formula ==="
        head -15 "$formula_file"
        echo "..."
    fi
    echo
    
    # Commit and push changes
    log "Committing changes to tap repository..."
    
    cd "$tap_dir"
    
    # Check if there are actually changes
    if git diff --quiet; then
        warn "No changes detected in formula"
        rm "$backup_file"
        cd - > /dev/null
        return 0
    fi
    
    # Commit changes
    git add Formula/wt.rb
    git commit -m "Update wt formula to v$version

- Update download URL to v$version release
- Update SHA256 checksum: $sha256
- Update version string and test assertions

Auto-generated by update-tap.sh script."
    
    # Push to GitHub
    git push origin main
    
    success "Tap updated and pushed to GitHub"
    success "Users can now upgrade with: brew upgrade wt"
    
    # Clean up backup
    rm "$backup_file"
    
    cd - > /dev/null
}

validate_version() {
    local version="$1"
    
    # Check version format
    if [[ ! $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        error "Invalid version format: $version (expected: X.Y.Z)"
        exit 1
    fi
    
    # Check if release exists
    local release_url="https://github.com/bwishan/wt/releases/tag/v$version"
    if ! curl -sf "$release_url" > /dev/null; then
        error "Release v$version not found at $release_url"
        error "Create the release first, then update the tap"
        exit 1
    fi
    
    success "Release v$version found"
}

main() {
    if [ $# -ne 1 ]; then
        usage
        exit 1
    fi
    
    local version="$1"
    
    # Validate environment
    if [ ! -f "Formula/wt.rb" ]; then
        error "Run this script from the wt project root directory"
        exit 1
    fi
    
    if ! command -v curl &> /dev/null; then
        error "curl not found - required for downloading release"
        exit 1
    fi
    
    if ! command -v git &> /dev/null; then
        error "git not found - required for committing changes"
        exit 1
    fi
    
    # Validate version and release
    validate_version "$version"
    
    # Update the tap
    update_tap_formula "$version"
    
    echo
    success "Homebrew tap successfully updated to v$version!"
    echo
    log "Next steps:"
    echo "1. Test the update: brew upgrade wt"
    echo "2. Verify installation: wt --version"
    echo "3. Check tap status: brew info wt"
}

main "$@"